### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by tangleiao** [sbinet/go-python#31]
hi  sbinet:
    While using go-python , occurred the error "fatal error: unexpected signal during runtime execution".  The error looks like c programming error. I am using python 2.7
    Can you have any suggestion?

   Thank you.

**Comment by tangleiao** [comment]
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x48 pc=0x7f468752708c]

runtime stack:
runtime.gothrow(0x106ee10, 0x2a)
        /usr/local/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 36 [syscall, locked to thread]:
runtime.cgocall_errno(0x416950, 0xc2083261a0, 0x0)
        /usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc208326180 sp=0xc208326158
github.com/sbinet/go-python._Cfunc_PyImport_ImportModule(0x7f46640008c0, 0x0)
        /data/tlt/go/src/github.com/sbinet/go-python/:758 +0x44 fp=0xc2083261a0 sp=0xc208326180
github.com/sbinet/go-python.PyImport_ImportModule(0xef93d0, 0x7, 0x0)
        /data/tlt/go/src/github.com/sbinet/go-python/utilities.go:166 +0x6d fp=0xc2083261d8 sp=0xc2083261a0
github.com/grafana/grafana/pkg/middleware.IsAlarmSignedIn(0xc2081c60c0, 0xc208326328)
        /data/tlt/go/src/github.com/grafana/grafana/pkg/middleware/auth.go:119 +0x233 fp=0xc2083262d8 sp=0xc2083261d8
github.com/grafana/grafana/pkg/middleware.func·002(0xc2081c60c0)
        /data/tlt/go/src/github.com/grafana/grafana/pkg/middleware/auth.go:81 +0x31 fp=0xc2083262f8 sp=0xc2083262d8
runtime.call16(0xc208352490, 0xc2080393c0, 0x800000008)
        /usr/local/go/src/runtime/asm_amd64.s:401 +0x45 fp=0xc208326310 sp=0xc2083262f8
reflect.Value.call(0xbe0be0, 0xc208352490, 0x13, 0xee31b0, 0x4, 0xc2083380a0, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:419 +0x10e5 fp=0xc208326628 sp=0xc208326310
reflect.Value.Call(0xbe0be0, 0xc208352490, 0x13, 0xc2083380a0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:296 +0xbc fp=0xc208326688 sp=0xc208326628
github.com/Unknwon/macaron/inject.(*injector).Invoke(0xc208358aa0, 0xbe0be0, 0xc208352490, 0x0, 0x0, 0x0, 0x0, 0x0)
        /data/tlt/go/src/github.com/Unknwon/macaron/inject/inject.go:102 +0x3c7 fp=0xc208326798 sp=0xc208326688
github.com/Unknwon/macaron.(*Context).run(0xc2081f0fc0)
        /data/tlt/go/src/github.com/Unknwon/macaron/context.go:113 +0x95 fp=0xc208326860 sp=0xc208326798
github.com/Unknwon/macaron.(*Context).Next(0xc2081f0fc0)
        /data/tlt/go/src/github.com/Unknwon/macaron/context.go:104 +0x33 fp=0xc208326870 sp=0xc208326860
github.com/grafana/grafana/pkg/middleware.func·009(0xc2081c60c0)
        /data/tlt/go/src/github.com/grafana/grafana/pkg/middleware/session.go:71 +0x37 fp=0xc2083268f0 sp=0xc208326870
runtime.call16(0xc208352480, 0xc2080393b8, 0x800000008)

**Comment by sbinet** [comment]
could you provide me with an as simple as possible reproducer?

**Comment by jjjachyty** [comment]
So do I，when i use goroutine to pyObject.CallFunction(xx,xx)

**Comment by sbinet** [comment]
@jjjachyty could you provide me with an as simple as possible reproducer?

**Comment by jjjachyty** [comment]
@sbinet I've been using  thrift RPC service replace this way，you can write  go bench test to call pyObject.CallFunction(xx,xx),This error will appear

**Comment by sbinet** [comment]
I believe you, of course, but having a minimal reproducer would greatly help debit the *exact* same issue you have.

**Comment by jjjachyty** [comment]
@sbinet 
main.go
``` 
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/sbinet/go-python"
)

func init() {
	err := python.Initialize()
	if err != nil {
		panic(err.Error())
	}
}

func main() {

	for index := 0; index < 5; index++ {
		go call()
	}
	time.Sleep(20 * time.Second)
}

func call() {
	flag := python.PyRun_SimpleString("import sys")
	fmt.Println("flag", flag)
	python.PyRun_SimpleString("sys.path.append('.')")

	m := python.PyImport_ImportModule("produrce")

	if m == nil {
		log.Fatalf("could not import 'kwargs'\n")
	}

	callProcedure := m.GetAttrString("callProcedure")
	if callProcedure == nil {
		log.Fatalf("could not getattr(kwargs, 'callProcedure')\n")
	}

	// keyword arguments
	url := python.PyString_FromString("tjlrm/tjlrm@172.168.171.200:1521/xe")
	kw := python.PyLong_FromLong(1519291183)
	name := python.PyString_FromString("PROC_TEST")

	out := callProcedure.CallFunction(url, name, kw)
	if out == nil {
		log.Fatalf("error calling foo(*args, **kwargs)\n", out)
	}
	returnFlag := python.PyTuple_GetItem(out, 0)
	returnMsg := python.PyTuple_GetItem(out, 1)

	fmt.Println("--------", python.PyLong_AsLong(returnFlag), python.PyString_AsString(returnMsg))
	//fmt.Printf("%s\n", str)
}

```
produrce.py
```
#! /usr/bin/env python
# -*- coding: utf-8 -*-
import cx_Oracle
import time
import os
import datetime
import sys


def callProcedure(url,prdocedureName,unixDate):
    os.environ['NLS_LANG'] = "American_America.AL32UTF8"
    try:
        conn = cx_Oracle.connect(url)
        cursor = conn.cursor()
        asofdate = datetime.datetime.strptime(time.strftime("%Y-%m-%d", time.localtime(unixDate)), '%Y-%m-%d')
        param4 = cursor.var(cx_Oracle.NUMBER)  # plsql出参

        param5 = cursor.var(cx_Oracle.STRING)  # plsql出参

        # args.append(param4,param5)
        # 调用存储过程
        cursor.callproc(prdocedureName, [asofdate,param4,param5])  # ['Nick', 'Nick, Good Morning!']

        return param4.getvalue(),param5.getvalue()
    except Exception as e:
        print("错误",e)
        return False,False,e.__str__()
    finally:
    # 资源关闭
        cursor.close()
        conn.close()

```

then this error will be appear
```fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff550b22c7]

runtime stack:
runtime.throw(0x40de253, 0x2a)
        /DATA/Work/CODE/GO/GOROOT/go/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
        /DATA/Work/CODE/GO/GOROOT/go/src/runtime/signal_unix.go:351 +0x2b8

goroutine 6 [syscall, locked to thread]:
runtime.cgocall(0x40a30f0, 0xc4200a8e88, 0xc4200a8e90)
        /DATA/Work/CODE/GO/GOROOT/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc4200a8e58 sp=0xc4200a8e18 pc=0x4004314```

**Comment by sbinet** [comment]
thanks @jjjachyty 

I see an invalid use of `go-python` (well, the `CPython` API, really):

you call concurrently multiple `CPython` API functions (through `go call()`). `CPython` is notoriously known for its GIL (the Global Interpreter Lock) that has to be held whenever one needs to make a call to the CPython API.

you need to make sure only one thread is calling back into CPython:
https://docs.python.org/2/c-api/init.html#thread-state-and-the-global-interpreter-lock

**Comment by yanchenghust** [comment]
I have the same problems, here is my solution:
after `python.Initialize()`，do `pyThreadState = python.PyEval_SaveThread()`。Each time you access to the python C API，`python.PyEval_RestoreThread(pyThreadState)` ... your code ...  `pyThreadState = python.PyEval_SaveThread()`

here is my sample code:

`var pyModule, ut, exec, compile *python.PyObject
var pyThreadState *python.PyThreadState

var PyStr = python.PyString_FromString
var GoStr = python.PyString_AS_STRING

func InitPy(pyModulePath string) {
	err := python.Initialize()
	if err != nil {
		panic(err.Error())
	}
	pyModule = ImportModule(pyModulePath, "python_runtime")
	ut = pyModule.GetAttrString("ut")
	exec = pyModule.GetAttrString("exec_code")
	compile = pyModule.GetAttrString("compile")
	logs.Debug("pyModule=%#v, ut=%#v, exec=%#v, compile=%#v", pyModule, ut, exec, compile)
	pyThreadState = python.PyEval_SaveThread()
}

func FinalizePy() {
	python.PyEval_RestoreThread(pyThreadState)
	python.Finalize()
	logs.Debug("finalized")
	logs.Flush()
}

func (r PythonRuntime) RunUt(ctx context.Context, code, input, output string) (*model.UtResult, error) {
	python.PyEval_RestoreThread(pyThreadState)
	utArgs := python.PyTuple_New(3)
	if output == "" {
		output = "None"
	}
	python.PyTuple_SetItem(utArgs, 0, PyStr(code))
	python.PyTuple_SetItem(utArgs, 1, PyStr(input))
	python.PyTuple_SetItem(utArgs, 2, PyStr(output))

	utResult := ut.Call(utArgs, python.Py_None)

	ret := &model.UtResult{}
	ret.Success = python.PyInt_AS_LONG(python.PyDict_GetItemString(utResult, "success")) == 1
	ret.ErrMsg = GoStr(python.PyDict_GetItemString(utResult, "msg"))
	ret.ExecOutput = GoStr(python.PyDict_GetItemString(utResult, "output"))
	pyThreadState = python.PyEval_SaveThread()
	return ret, nil
}`

**Comment by sbinet** [comment]
yes, @yanchenghust , that's another way to deal with the GIL.
marking this as "resolved".

**Comment by Sitrone** [comment]
> I have the same problems, here is my solution:
> after `python.Initialize()`，do `pyThreadState = python.PyEval_SaveThread()`。
> Each time you access to the python C API，do as follows:
> 
> ```
> python.PyEval_RestoreThread(pyThreadState)
> // your code ...  
> pyThreadState = python.PyEval_SaveThread()
> ```
> 
> here is my sample code:
> 
> ```go
> var pyModule, ut, exec, compile *python.PyObject
> var pyThreadState *python.PyThreadState
> var PyStr = python.PyString_FromString
> var GoStr = python.PyString_AS_STRING
> 
> func InitPy(pyModulePath string) {
> 	err := python.Initialize()
> 	if err != nil {
> 		panic(err.Error())
> 	}
> 	pyModule = ImportModule(pyModulePath, "python_runtime")
> 	ut = pyModule.GetAttrString("ut")
> 	exec = pyModule.GetAttrString("exec_code")
> 	compile = pyModule.GetAttrString("compile")
> 	logs.Debug("pyModule=%#v, ut=%#v, exec=%#v, compile=%#v", pyModule, ut, exec, compile)
> 	pyThreadState = python.PyEval_SaveThread()
> }
> func FinalizePy() {
> 	python.PyEval_RestoreThread(pyThreadState)
> 	python.Finalize()
> 	logs.Debug("finalized")
> 	logs.Flush()
> }
> func (r PythonRuntime) RunUt(ctx context.Context, code, input, output string) (*model.UtResult, error) {
> 	python.PyEval_RestoreThread(pyThreadState)
> 	utArgs := python.PyTuple_New(3)
> 	if output == "" {
> 		output = "None"
> 	}
> 	python.PyTuple_SetItem(utArgs, 0, PyStr(code))
> 	python.PyTuple_SetItem(utArgs, 1, PyStr(input))
> 	python.PyTuple_SetItem(utArgs, 2, PyStr(output))
> 	utResult := ut.Call(utArgs, python.Py_None)
> 	ret := &model.UtResult{}
> 	ret.Success = python.PyInt_AS_LONG(python.PyDict_GetItemString(utResult, "success")) == 1
> 	ret.ErrMsg = GoStr(python.PyDict_GetItemString(utResult, "msg"))
> 	ret.ExecOutput = GoStr(python.PyDict_GetItemString(utResult, "output"))
> 	pyThreadState = python.PyEval_SaveThread()
> 	return ret, nil
> }
> ```

Finally I fixed it by add a global mutex lock, it seems that ,this doesn't work.

**Comment by kingangelAOA** [comment]
`
package kyara

import (
	"time"
)

//Pool pool object
type Pool struct {
	GoroutineNum         int
	ConcurrentGoroutines chan struct{}
	Total                int
	Result               chan error
	FinishCallback       func()
	done                 chan bool
	waitForAllJobs       chan bool
	task                 func() error
	finished             bool
	runTime              int64
	runNum               int64
}

//Init init pool
func (p *Pool) Init(GoroutineNum int, total int) {
	p.Total = total
	p.GoroutineNum = GoroutineNum
	p.ConcurrentGoroutines = make(chan struct{}, p.GoroutineNum)
	p.Result = make(chan error, total)
	p.done = make(chan bool)
	p.waitForAllJobs = make(chan bool)
	p.initConcurrentGoroutines()
	p.finished = false
}

//AddTask add task
func (p *Pool) AddTask(task func() error) {
	p.task = task
}

func (p *Pool) initConcurrentGoroutines() {
	for i := 0; i < int(p.GoroutineNum); i++ {
		p.ConcurrentGoroutines <- struct{}{}
	}
}

//Start start pool

func (p *Pool) Start() {
	go func() {
		for !p.finished {
			<-p.done
			if !p.finished {
				p.ConcurrentGoroutines <- struct{}{}
			}
		}
	}()

	go func() {
		nowTime := time.Now().UnixNano() / int64(time.Millisecond)
		runNum := int64(1)
		for !p.finished {
			<-p.ConcurrentGoroutines
			go func() {
				if err := p.task(); err != nil {
					p.Result <- err
				} else {
					p.runTime = time.Now().UnixNano()/int64(time.Millisecond) - nowTime
					p.runNum = runNum
					runNum++
				}
				if !p.finished {
					p.done <- true
				}
			}()
		}
	}()
}

//Stop step pool
func (p *Pool) stop() {
	p.finished = true
	close(p.ConcurrentGoroutines)
	close(p.done)
}

func (p *Pool) SetFinishCallback(fun func()) {
	p.FinishCallback = fun
}

`
`
package kyara

import (
	"encoding/json"
	"github.com/sbinet/go-python"
	"regexp"
	"strings"
)

var pyThreadState *python.PyThreadState

//var pyThreadState *python3.PyThreadState
func init() {
	err := python.Initialize()
	if err != nil {
		panic(err.Error())
	}
	pyThreadState = python.PyEval_SaveThread()
}

type ScriptResult struct {
	result interface{}
}

type Scripts interface {
	InitScript() error
	Run()
}

type PythonScriptList struct {
	scripts   []PythonScript
	moduleMap map[string]*python.PyObject
}

type PythonScript struct {
	Name       string `json:"name"`
	Source     string `json:"source"`
	ModuleName string `json:"moduleName"`
}

func (p *PythonScriptList) InitScript() error {
	python.PyEval_RestoreThread(pyThreadState)
	for _, ps := range p.scripts {
		source := python.PyString_FromString(ps.Source)
		filename := python.PyString_FromString(ps.ModuleName)
		mode := python.PyString_FromString("exec")
		builtins := python.PyEval_GetBuiltins()
		compile := python.PyDict_GetItemString(builtins, "compile")
		code := compile.CallFunction(source, filename, mode)
		module := python.PyImport_ExecCodeModule("test_module", code)
		if module == nil {
			return ErrLoadPythonModule
		}
		p.moduleMap[ps.ModuleName] = module
	}

	pyThreadState = python.PyEval_SaveThread()
	return nil
}

func (p *PythonScriptList) Run(moduleName, methodArgs string) error {
	python.PyEval_RestoreThread(pyThreadState)
	if module, ok := p.moduleMap[moduleName]; ok {
		method, argsList, err := getMethodArgs(methodArgs)
		if err != nil {
			return err
		}
		result := module.CallMethod(method, argsList...)
		//fmt.Println(python.PyString_AsString(result))
		defer result.DecRef()
	} else {
		return ErrModuleNotExist
	}
	pyThreadState = python.PyEval_SaveThread()
	return nil
}

func getMethodArgs(methodArgs string) (string, []interface{}, error) {
	r := regexp.MustCompile(`\((.*?)\)`)
	params := r.FindAllStringSubmatch(methodArgs, -1)
	method := strings.Split(methodArgs, "(")[0]
	var argsList []interface{}
	if len(params) != 1 {
		return "", nil, ErrMethodArgsFormat
	}
	param := params[0]
	args := param[1]
	args = strings.Replace(args, " ", "", -1)
	if args != "" {
		if strings.Contains(args, ",") {
			strList := strings.Split(args, ",")
			for _, v := range strList {
				argsList = append(argsList, v)
			}
		} else {
			argsList = []interface{}{args}
		}
	} else {
		argsList = []interface{}{}
	}
	return method, argsList, nil
}

func JsonToPythonScriptList(j string) (*PythonScriptList, error) {
	var p []PythonScript
	if err := json.Unmarshal([]byte(j), &p); err != nil {
		return nil, err
	}
	psl := &PythonScriptList{
		scripts: p,
		moduleMap: map[string]*python.PyObject{},
	}
	return psl, nil
}

`

`func TestHigh(t *testing.T) {
	var p Pool
	num := 2000
	p.Init(num, num)
	//url := fmt.Sprintf(`http://10.40.46.23:12138/get1?max=100&min=20`)
	//client := &fasthttp.Client{
	//	MaxConnsPerHost: num,
	//}
	data := `[{
		"name": "test",
		"source": "import json\ndef test():\n  return 'test'",
		"moduleName": "test"
		
	}]`
	psl, err := JsonToPythonScriptList(data)
	if err == nil {
		if err := psl.InitScript(); err == nil {

		} else {
			fmt.Println(err)
		}
	} else {
		fmt.Println(err)
	}
	p.AddTask(func() error {
		er := psl.Run("test", "test()")
		if er != nil {
			fmt.Println(er)
		}
		return nil
	})
	p.Start()
	select {

	}
}
`
python.PyEval_RestoreThread(pyThreadState) error  

stack:
goroutine 4224863 [syscall]:
github.com/sbinet/go-python._Cfunc_PyEval_RestoreThread(0xbee5e0)
	_cgo_gotypes.go:2642 +0x41
github.com/sbinet/go-python.PyEval_RestoreThread.func1(0xc00052eb68)
	/home/jyan/work/go_work/src/github.com/sbinet/go-python/python.go:64 +0x5e
github.com/sbinet/go-python.PyEval_RestoreThread(0xc00052eb68)
	/home/jyan/work/go_work/src/github.com/sbinet/go-python/python.go:64 +0x2b
kyara.(*PythonScriptList).Run(0xc0000ae140, 0x57cdee, 0x4, 0x57d15e, 0x6, 0x0, 0x0)
	/home/jyan/work/go_work/src/kyara/script.go:62 +0x3c
kyara.TestHigh.func1(0x0, 0x0)
	/home/jyan/work/go_work/src/kyara/script_test.go:71 +0x58
kyara.(*Pool).Start.func2.1(0xc0000a4240, 0x16c03f52e73, 0xc00009e298)
	/home/jyan/work/go_work/src/kyara/pool.go:63 +0x2f
created by kyara.(*Pool).Start.func2
	/home/jyan/work/go_work/src/kyara/pool.go:62 +0x119

**Comment by dhanush** [comment]
I am also trying the same as @yanchenghust and I still get the same error.  Is this type of conversion important as well 

`GoStr(python.PyDict_GetItemString(utResult, "msg"))`
